### ISSUE TITLE
why is this project licensed under GPLv3 and not MIT?

### ISSUE THREAD

**Issue by ghost** [CyberBoyAyush/JS-Portfolio#2]
Hi.

I wonder if there is a good reason why the open project is licensed under GPLv3 and not MIT. Why is this project licensed under GPLv3 and not MIT? (I would like to know this question out of curiosity).

**Comment by CyberBoyAyush** [comment]
Because this is a fork edited repo with some addition.

**Comment by ghost** [comment]
> Because this is a fork edited repo with some addition.

thanks for comment.
